name: daily-run
on:
  schedule:
    - cron: "0 5 * * *"  # ~06:00 Zagreb
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "uv.lock"
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install uv
      - run: uv pip install --system --no-cache .

      - name: run script
        run: python main.py
        working-directory: gablec_script
